/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Dan Shue. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * @module Submission/ChangelogScreen
 * @description Dedicated changelog generation and editing screen for extension updates.
 *
 * This screen is shown only when the user is submitting an update to an existing
 * catalog extension. It fetches the previous README from GitHub, uses AI to diff
 * it against the new README, and produces a structured changelog that gets bundled
 * into the submission.
 *
 * @since 0.1.0
 */

import { Setting, ButtonComponent } from "obsidian";
import type { ScreenContext, ScreenCallbacks } from "./types";

/**
 * Renders the changelog step for extension updates.
 *
 * @param container - The parent HTML element to render into
 * @param context - Shared screen context with submission state
 * @param callbacks - Navigation and action callbacks
 * @param renderNavigationButtons - Helper to render Back / Next buttons
 * @param onGenerateChangelog - Callback that fetches previous data and generates the changelog via AI
 *
 * @example
 * ```typescript
 * renderChangelogScreen(contentEl, context, callbacks, renderNav, async () => {
 *   // fetch + generate changelog logic
 * });
 * ```
 */
export function renderChangelogScreen(
	container: HTMLElement,
	context: ScreenContext,
	callbacks: ScreenCallbacks,
	renderNavigationButtons: (container: HTMLElement, showBack: boolean, showNext: boolean) => void,
	onGenerateChangelog: () => Promise<void>
): void {
	container.createEl("h2", { text: "Version Changelog" });
	container.createEl("p", {
		text: `You are updating an existing extension from v${context.catalogVersion || "?"} to v${context.submissionData.version || "?"}. `
			+ "Generate or write a changelog describing what changed in this version."
	});

	// ── Generate button ──────────────────────────────────────────────────
	new Setting(container)
		.setName("Generate changelog")
		.setDesc(
			"Uses AI to compare your current README with the previously published version and produce a structured changelog."
		)
		.addButton((button: ButtonComponent) => {
			button
				.setButtonText(
					context.isGeneratingChangelog ? "Generating…" : "Generate with AI"
				)
				.setClass("btn-ai")
				.setDisabled(context.isGeneratingChangelog)
				.onClick(async () => {
					await onGenerateChangelog();
				});
		});

	// ── Editable textarea ────────────────────────────────────────────────
	const textareaWrapper = container.createDiv({ cls: "setting-item-stacked" });
	textareaWrapper.createEl("label", {
		text: "Changelog content",
		cls: "setting-item-name"
	});
	textareaWrapper.createEl("p", {
		text: "Edit the generated changelog or write your own. Markdown formatting is supported.",
		cls: "setting-item-description"
	});

	context.changelogInput = textareaWrapper.createEl("textarea", {
		cls: "stacked-textarea changelog-textarea",
		attr: {
			placeholder: "## 1.1.0\n\n### Added\n- New feature X\n\n### Fixed\n- Bug in Y",
			rows: "12"
		}
	});
	context.changelogInput.value =
		context.generatedChangelog || context.submissionData.changelog || "";

	// Persist edits back to submission data
	context.changelogInput.addEventListener("input", () => {
		context.submissionData.changelog = context.changelogInput?.value ?? "";
	});

	// ── Info box ─────────────────────────────────────────────────────────
	const infoContainer = container.createDiv({ cls: "validation-info" });
	infoContainer.createEl("p", {
		text: context.generatedChangelog
			? "💡 Changelog generated by AI. Review and edit as needed before proceeding."
			: "💡 Click \"Generate with AI\" to automatically create a changelog, or type one manually."
	});

	// Message container for status feedback
	container.createDiv({ cls: "step-message-container" });

	// Navigation buttons
	renderNavigationButtons(container, true, true);
}
